"use client";

import { useState, useTransition } from "react";
import { generateSummary } from "../app/title/[id]/ai-actions";

export default function AiSummary({
  titleId,
  initialSummary,
  isLoggedIn,
}: {
  titleId: number;
  initialSummary: string | null;
  isLoggedIn: boolean;
}) {
  const [summary, setSummary] = useState<string | null>(initialSummary);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleGenerate() {
    setError(null);
    startTransition(async () => {
      const result = await generateSummary(titleId);
      if (result.error) {
        setError(result.error);
      } else {
        setSummary(result.summary);
      }
    });
  }

  if (!summary && !isLoggedIn) {
    return null;
  }

  return (
    <div className="relative overflow-hidden rounded-2xl">
      <div
        aria-hidden
        className="pointer-events-none absolute -inset-px rounded-2xl bg-gradient-to-br from-purple-500/50 via-fuchsia-500/15 to-purple-500/35 opacity-90 blur-[2px]"
      />
      <div className="relative overflow-hidden rounded-[calc(1rem-1px)] border border-purple-500/20 bg-gradient-to-br from-purple-500/8 via-surface to-background-elevated shadow-[0_1px_0_rgba(255,255,255,0.03)_inset]">
        <div
          aria-hidden
          className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-purple-500/18 blur-3xl"
        />
        <div
          aria-hidden
          className="pointer-events-none absolute -bottom-14 -left-10 h-36 w-36 rounded-full bg-fuchsia-500/10 blur-3xl"
        />
        <div className="relative p-4 sm:p-5">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-purple-500/90 to-fuchsia-500/70 text-background shadow-[0_0_30px_-8px_rgba(168,85,247,0.6)] sm:h-9 sm:w-9 sm:rounded-xl">
                <span aria-hidden className="text-[13px] sm:text-sm">
                  ✨
                </span>
              </span>
              <div>
                <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-purple-300/90 sm:text-xs">
                  AI community summary
                </p>
                {summary && (
                  <p className="mt-0.5 text-[11px] text-muted sm:text-xs">
                    From community ratings, screen times &amp; reviews
                  </p>
                )}
              </div>
            </div>
            {isLoggedIn && (
              <button
                type="button"
                disabled={isPending}
                onClick={handleGenerate}
                className="btn bg-brand text-background hover:bg-brand-hover disabled:cursor-not-allowed disabled:opacity-60 py-1.5 text-xs sm:py-2 sm:text-sm"
              >
                {isPending
                  ? "Generating…"
                  : summary
                    ? "Refresh"
                    : "Generate"}
              </button>
            )}
          </div>

          {summary ? (
            <div className="mt-4 rounded-xl border border-purple-500/12 bg-background/50 p-4 sm:mt-5 sm:p-5">
              <p className="text-base leading-relaxed text-foreground/90 sm:text-[15px]">
                {summary}
              </p>
            </div>
          ) : (
            <p className="mt-4 rounded-xl border border-dashed border-purple-500/20 bg-background/20 p-4 text-sm text-muted sm:mt-5 sm:p-5">
              No summary yet. Generate one from this movie&apos;s ratings, screen
              times and reviews.
            </p>
          )}

          {error && (
            <p className="mt-4 rounded-lg bg-rose-500/10 px-3 py-2 text-sm text-rose-400">
              {error}
            </p>
          )}

          <p className="mt-4 text-[11px] leading-relaxed text-muted sm:text-xs">
            Generated by AI from community data. It may contain mistakes.
          </p>
        </div>
      </div>
    </div>
  );
}
