"use client";

import { useState, useTransition } from "react";
import { generateSummary } from "../app/title/[id]/ai-actions";

export default function AiSummary({
  titleId,
  initialSummary,
  isLoggedIn,
}: {
  titleId: number;
  initialSummary: string | null;
  isLoggedIn: boolean;
}) {
  const [summary, setSummary] = useState<string | null>(initialSummary);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleGenerate() {
    setError(null);
    startTransition(async () => {
      const result = await generateSummary(titleId);
      if (result.error) {
        setError(result.error);
      } else {
        setSummary(result.summary);
      }
    });
  }

  if (!summary && !isLoggedIn) {
    return null;
  }

  return (
    <div className="relative overflow-hidden rounded-2xl border border-gold/15 bg-gradient-to-br from-gold/8 via-surface to-background-elevated shadow-[0_1px_0_rgba(255,255,255,0.03)_inset]">
      <div
        aria-hidden
        className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-gold/10 blur-3xl"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute -bottom-16 -left-12 h-40 w-40 rounded-full bg-gold/5 blur-3xl"
      />
      <div className="relative p-5 sm:p-6">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-gold/90 to-gold-muted text-background shadow-[0_0_30px_-10px_rgba(234,190,85,0.6)] sm:h-10 sm:w-10">
              <span aria-hidden>✨</span>
            </span>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">
                AI Community Summary
              </p>
              {summary && (
                <p className="mt-0.5 text-[11px] text-muted sm:text-xs">
                  Aggregated from ratings, screen times &amp; reviews
                </p>
              )}
            </div>
          </div>
          {isLoggedIn && (
            <button
              type="button"
              disabled={isPending}
              onClick={handleGenerate}
              className="btn btn-gold px-3.5 py-1.5 text-xs sm:px-4 sm:py-2 sm:text-sm"
            >
              {isPending
                ? "Generating…"
                : summary
                  ? "Refresh"
                  : "Generate"}
            </button>
          )}
        </div>

        {summary ? (
          <div className="mt-5 rounded-xl border border-border bg-background/60 p-4 sm:p-5">
            <p className="text-sm leading-relaxed text-foreground/90 sm:text-[15px]">
              {summary}
            </p>
          </div>
        ) : (
          <p className="mt-5 rounded-xl border border-dashed border-border-strong bg-background/20 p-4 text-sm text-muted sm:p-5">
            No summary yet. Generate one from this movie&apos;s ratings, screen
            times and reviews.
          </p>
        )}

        {error && (
          <p className="mt-4 rounded-lg bg-danger/10 px-3 py-2 text-sm text-danger">
            {error}
          </p>
        )}

        <p className="mt-5 flex items-center gap-1.5 text-xs text-muted sm:text-[13px]">
          <span aria-hidden>⚠</span> Generated by AI from community data. It may
          contain mistakes.
        </p>
      </div>
    </div>
  );
}