"use client";

import { useState, useTransition } from "react";
import { generateSummary } from "../app/title/[id]/ai-actions";

export default function AiSummary({
  titleId,
  initialSummary,
  isLoggedIn,
}: {
  titleId: number;
  initialSummary: string | null;
  isLoggedIn: boolean;
}) {
  const [summary, setSummary] = useState<string | null>(initialSummary);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleGenerate() {
    setError(null);
    startTransition(async () => {
      const result = await generateSummary(titleId);
      if (result.error) {
        setError(result.error);
      } else {
        setSummary(result.summary);
      }
    });
  }

  if (!summary && !isLoggedIn) {
    return null;
  }

  return (
    <div className="mt-6 rounded-lg border border-purple-500/30 bg-purple-500/5 p-4">
      <p className="text-xs font-medium uppercase tracking-wide text-purple-300">
        ✨ AI community summary
      </p>

      {summary ? (
        <p className="mt-2 text-sm text-neutral-200">{summary}</p>
      ) : (
        <p className="mt-2 text-sm text-muted">
          No summary yet. Generate one from this movie&apos;s ratings, screen
          times and reviews.
        </p>
      )}

      {isLoggedIn && (
        <button
          type="button"
          disabled={isPending}
          onClick={handleGenerate}
          className="mt-3 rounded-md bg-brand px-4 py-1.5 text-sm font-medium hover:bg-brand-hover disabled:opacity-50"
        >
          {isPending
            ? "Generating..."
            : summary
              ? "Refresh summary"
              : "Generate summary"}
        </button>
      )}

      {error && <p className="mt-2 text-sm text-red-400">{error}</p>}

      <p className="mt-2 text-xs text-muted">
        Generated by AI from community data. It may contain mistakes.
      </p>
    </div>
  );
}